# データベースに Postgresql を使用する。
spring.datasource.driver-class-name=org.postgresql.Driver

# ファイルにデータベースを作成する場合(<user>は自分のユーザ名)
spring.datasource.url=jdbc:postgresql://database:5432/trainingapp
spring.datasource.username=trainingapp
spring.datasource.password=trainingapp

# データベース初期化モードの設定。
# spring.sql.init.mode=always
