# データベースに Postgresql を使用する。
spring.datasource.driver-class-name=org.postgresql.Driver

# ファイルにデータベースを作成する場合(<user>は自分のユーザ名)
spring.datasource.url=jdbc:postgresql://database:5432/trainingapp
spring.datasource.username=trainingapp
spring.datasource.password=trainingapp

# src/main/resources/schema.sqlからデータベースの初期化を行う場合は、以下のコメントを外す
# spring.sql.init.mode=always

# SQLのログを出力する
spring.jpa.show-sql=true

# ThymeleafのテンプレートキャッシュをOFFにする
# (デバッグ時、テンプレート修正した際に即時反映させるため)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:webapp/src/main/resources/templates/